// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ASPNETCore8ApiIOracleEf.Models;

public partial class Employee
{
    public decimal Id { get; set; }

    public string? Name { get; set; }

    public string? Address { get; set; }

    public byte[]? Photo { get; set; }
}